apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: avinashsachdewani/node-hello-world:dev
        imagePullPolicy: IfNotPresent
        name: hello-world
        ports:
        - containerPort: 3000